downloader:
  #size in ko related to a single segment
  minsize: 10485760  #10MB
  maxsize: 524288000  #500MB
  #max number of concurrent thread downloading
  maxconcurrency: 5
  maxretry: 3
  chunksize: 2097152
  #useadaptivescheduler: true

storage:
  buffersize: 2097152 #2MB
  folder: /Users/stephane/Downloads/aspettaaspera/